import { computed } from 'vue'

type Translate = (key: string) => string

export function useCanvasLabels(t: Translate) {
  const toolbar = computed(() => ({
    toolbar: t('workspace.canvas.toolbar'),
    select: t('workspace.canvas.select'),
    hand: t('workspace.canvas.hand'),
    text: t('workspace.canvas.addText'),
    note: t('workspace.canvas.richNote'),
    'note-link': t('workspace.canvas.noteLink'),
    frame: t('workspace.canvas.frame'),
    mindmap: t('workspace.canvas.mindMap'),
    rectangle: t('workspace.canvas.rectangle'),
    ellipse: t('workspace.canvas.ellipse'),
    diamond: t('workspace.canvas.diamond'),
    connector: t('workspace.canvas.connector'),
    pen: t('workspace.canvas.pen'),
    highlighter: t('workspace.canvas.highlighter'),
    eraser: t('workspace.canvas.eraser'),
    image: t('workspace.canvas.image'),
    zoomIn: t('workspace.canvas.zoomIn'),
    zoomOut: t('workspace.canvas.zoomOut'),
    fit: t('workspace.canvas.fit'),
    undo: t('workspace.canvas.undo'),
    redo: t('workspace.canvas.redo'),
    fullscreen: t('workspace.canvas.fullscreen'),
    present: t('workspace.canvas.present'),
    export: t('workspace.canvas.export'),
  }))
  const properties = computed(() => ({
    properties: t('workspace.canvas.properties'),
    fill: t('workspace.canvas.fill'),
    stroke: t('workspace.canvas.stroke'),
    strokeWidth: t('workspace.canvas.strokeWidth'),
    opacity: t('workspace.canvas.opacity'),
    fontSize: t('workspace.canvas.fontSize'),
    textColor: t('workspace.canvas.textColor'),
    fontFamily: t('workspace.canvas.fontFamily'),
    fontSans: t('workspace.canvas.fontSans'),
    fontSerif: t('workspace.canvas.fontSerif'),
    fontMono: t('workspace.canvas.fontMono'),
    fontHandwriting: t('workspace.canvas.fontHandwriting'),
    rotation: t('workspace.canvas.rotation'),
    alt: t('workspace.canvas.alt'),
    connectAnchor: t('workspace.canvas.connectAnchor'),
    routing: t('workspace.canvas.routing'),
    straight: t('workspace.canvas.straight'),
    orthogonal: t('workspace.canvas.orthogonal'),
    bezier: t('workspace.canvas.bezier'),
    startCap: t('workspace.canvas.startCap'),
    endCap: t('workspace.canvas.endCap'),
    none: t('workspace.canvas.none'),
    arrow: t('workspace.canvas.arrow'),
    dot: t('workspace.canvas.dot'),
    left: t('workspace.canvas.alignLeft'),
    center: t('workspace.canvas.alignCenter'),
    right: t('workspace.canvas.alignRight'),
    top: t('workspace.canvas.alignTop'),
    middle: t('workspace.canvas.alignMiddle'),
    bottom: t('workspace.canvas.alignBottom'),
    distributeHorizontal: t('workspace.canvas.distributeHorizontal'),
    distributeVertical: t('workspace.canvas.distributeVertical'),
    duplicate: t('workspace.canvas.duplicate'),
    front: t('workspace.canvas.bringFront'),
    forward: t('workspace.canvas.bringForward'),
    backward: t('workspace.canvas.sendBackward'),
    back: t('workspace.canvas.sendBack'),
    group: t('workspace.canvas.group'),
    ungroup: t('workspace.canvas.ungroup'),
    lock: t('workspace.canvas.lock'),
    unlock: t('workspace.canvas.unlock'),
    frameTitle: t('workspace.canvas.frameTitle'),
    presentationOrder: t('workspace.canvas.presentationOrder'),
    openLinkedNote: t('workspace.canvas.openLinkedNote'),
    addMindMapChild: t('workspace.canvas.addMindMapChild'),
    layoutMindMap: t('workspace.canvas.layoutMindMap'),
  }))
  const overlays = computed(() => ({
    rotate: t('workspace.canvas.rotate'),
    connectorFrom: t('workspace.canvas.connectorFrom'),
    connectorTo: t('workspace.canvas.connectorTo'),
    editText: t('workspace.canvas.editText'),
    editRichText: t('workspace.canvas.editRichText'),
  }))
  function frame(collapsed: boolean) {
    return {
      label: t('workspace.canvas.document'),
      collapsedHint: t('workspace.canvas.collapsedHint'),
      toggleLabel: collapsed ? t('workspace.canvas.expand') : t('workspace.canvas.collapse'),
    }
  }
  return { toolbar, properties, overlays, frame }
}
